//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost_Favorites
    {
        public int BlogFavouriteId { get; set; }
        public Nullable<int> BlogId { get; set; }
        public string UserId { get; set; }
        public bool IsFavorite { get; set; }
        public bool IsLike { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BlogPost BlogPost { get; set; }
    }
}
